CREATE TABLE eg_ind_registration(
  id character varying(64),
  individualId character varying(64),
  tenantId character varying(64),
  clientReferenceId character varying(64),
  givenName character varying(64),
  familyName character varying(64),
  otherNames character varying(64),
  dateOfBirth date,
  gender character varying(10),
  bloodGroup character varying(3),
  mobileNumber character varying(20),
  altContactNumber character varying(16),
  email character varying(100),
  fatherName character varying(100),
  husbandName character varying(100),
  relationship character varying(100),
  photo text,
  additionalFields jsonb,
  rowVersion bigint,
  createdBy character varying(64),
  lastModifiedBy character varying(64),
  createdTime bigint,
  lastModifiedTime bigint,
  CONSTRAINT uk_eg_ind_registration UNIQUE (id)
);
